### ISSUE TITLE
README is unstructured regarding type of information source

### ISSUE THREAD

**Issue by matu3ba** [tensorush/Computer-Scientists-Toolkit#1]
links to repo, youtube links and website links are mixed and from context is unclear why it is relevant or not.
Do you intend this to be somewhat specific? Since currently there is no clear focus on things to excel.

For example, I did port and improve compiler_rt of zig and have here an [extensive list of stuff](https://github.com/ziglang/zig/issues/1290#issuecomment-903153201).
Usually knowledge is cluttered in different books of competing authors, so only providing a link is never sufficient.
The ideal solution would be like Knuths book (TAOCP) arguing optimal performance representable in a portable way and list the different techniques.

**Comment by tensorush** [comment]
Great work on Zig! This list of learning resources is intended as a compilation of links I found useful learning about algorithms and data structures in C++, which explains why it seems so general. It is there mostly for personal reference, just as this repo is. If anyone else finds it useful then I'm glad to help.
